---
apiVersion: v1
kind: Service
metadata:
  name: quickpizza-frontend
spec:
  type: LoadBalancer
  selector:
    app.k8s.io/name: quickpizza
    app.kubernetes.io/instance: frontend-gateway
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
      nodePort: 30333
---
apiVersion: v1
kind: Service
metadata:
  name: quickpizza-config
spec:
  type: ClusterIP
  selector:
    app.k8s.io/name: quickpizza
    app.kubernetes.io/instance: config
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: quickpizza-ws
spec:
  type: ClusterIP
  selector:
    app.k8s.io/name: quickpizza
    app.kubernetes.io/instance: ws
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: quickpizza-catalog
spec:
  type: ClusterIP
  selector:
    app.k8s.io/name: quickpizza
    app.kubernetes.io/instance: catalog
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: quickpizza-copy
spec:
  type: ClusterIP
  selector:
    app.k8s.io/name: quickpizza
    app.kubernetes.io/instance: copy
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: quickpizza-recs
spec:
  type: ClusterIP
  selector:
    app.k8s.io/name: quickpizza
    app.kubernetes.io/instance: recs
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
