x-quickpizza-env-common: &quickpizza-env-common
  QUICKPIZZA_OTLP_ENDPOINT: http://alloy:4318
  QUICKPIZZA_TRUST_CLIENT_TRACEID: true
  QUICKPIZZA_ENABLE_ALL_SERVICES: 0 # 0 for microservice mode
  QUICKPIZZA_CATALOG_ENDPOINT: http://catalog:3333
  QUICKPIZZA_COPY_ENDPOINT: http://copy:3333
  QUICKPIZZA_WS_ENDPOINT: http://ws:3333
  QUICKPIZZA_RECOMMENDATIONS_ENDPOINT: http://recommendations:3333
  QUICKPIZZA_CONFIG_ENDPOINT: http://config:3333
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=${DEPLOYMENT_ENVIRONMENT:-development},service.version=quickpizza-local"

name: quickpizza
services:
  alloy:
    image: grafana/alloy:v1.12.0
    container_name: alloy
    labels:
      - "service.type=instrumentation"
    volumes:
      - "./deployments/docker-compose/grafana-local-stack/${ALLOY_FILE_NAME:-config.alloy}:/config.alloy:Z"
      - "${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock"
    command:
      - run
      - /config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --stability.level=public-preview
    ports:
      - "12345:12345"
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    environment:
      QUICKPIZZA_HOST: quickpizza:3333
      METRICS_ENDPOINT: http://prometheus:9090/api/v1/write
      TRACES_ENDPOINT: http://tempo:4317
      LOGS_ENDPOINT: http://loki:3100/loki/api/v1/push
      PROFILES_ENDPOINT: http://pyroscope:4040
      DEPLOYMENT_ENVIRONMENT: ${DEPLOYMENT_ENVIRONMENT:-development}
      # Default uses the same DB connection as the Quickpizza service. Use empty string to disable.
      DB_O11Y_CONNECTION: "${DB_O11Y_CONNECTION-postgres://postgres:postgres@quickpizza-db:5432/quickpizza_db?sslmode=disable}"
      SERVICE_NAMESPACE: "${SERVICE_NAMESPACE:-quickpizza}"
      DB_SERVICE_NAME: "quickpizza-db"
    depends_on:
      - prometheus
      - tempo
      - pyroscope
      - catalog
      - config
      - copy
      - public-api
      - recommendations
      - ws
      - grpc

  catalog:
    image: ${QUICKPIZZA_IMAGE:-ghcr.io/grafana/quickpizza-local:0.15.20}
    container_name: catalog
    labels:
      - "service.type=application"
      - "service.namespace=${SERVICE_NAMESPACE:-quickpizza}"
    environment:
      <<: *quickpizza-env-common
      QUICKPIZZA_ENABLE_CATALOG_SERVICE: "1"
      QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID: "catalog"
      QUICKPIZZA_OTEL_SERVICE_NAME: "catalog"
      # QUICKPIZZA_DB unset set to postgres. If empty, set to sqlite.
      QUICKPIZZA_DB: "${QUICKPIZZA_DB-postgres://postgres:postgres@quickpizza-db:5432/quickpizza_db?sslmode=disable}"
    depends_on:
      quickpizza-db:
        condition: service_healthy

  config:
    image: ${QUICKPIZZA_IMAGE:-ghcr.io/grafana/quickpizza-local:0.15.20}
    container_name: config
    labels:
      - "service.type=application"
      - "service.namespace=${SERVICE_NAMESPACE:-quickpizza}"
    environment:
      <<: *quickpizza-env-common
      QUICKPIZZA_ENABLE_CONFIG_SERVICE: "1"
      QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID: "config"
      QUICKPIZZA_OTEL_SERVICE_NAME: "config"
  copy:
    image: ${QUICKPIZZA_IMAGE:-ghcr.io/grafana/quickpizza-local:0.15.20}
    container_name: copy
    labels:
      - "service.type=application"
      - "service.namespace=${SERVICE_NAMESPACE:-quickpizza}"
    environment:
      <<: *quickpizza-env-common
      QUICKPIZZA_ENABLE_COPY_SERVICE: "1"
      QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID: "copy"
      QUICKPIZZA_OTEL_SERVICE_NAME: "copy"
      # QUICKPIZZA_DB unset set to postgres. If empty, set to sqlite.
      QUICKPIZZA_DB: "${QUICKPIZZA_DB-postgres://postgres:postgres@quickpizza-db:5432/quickpizza_db?sslmode=disable}"
    depends_on:
      quickpizza-db:
        condition: service_healthy
      catalog:
        condition: service_started

  public-api:
    image: ${QUICKPIZZA_IMAGE:-ghcr.io/grafana/quickpizza-local:0.15.20}
    container_name: public-api
    labels:
      - "service.type=application"
      - "service.namespace=${SERVICE_NAMESPACE:-quickpizza}"
    ports:
      - "3333:3333"
    environment:
      <<: *quickpizza-env-common
      QUICKPIZZA_ENABLE_PUBLIC_API_SERVICE: "1"
      QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID: "public-api"
      QUICKPIZZA_OTEL_SERVICE_NAME: "public-api"

  recommendations:
    image: ${QUICKPIZZA_IMAGE:-ghcr.io/grafana/quickpizza-local:0.15.20}
    container_name: recommendations
    labels:
      - "service.type=application"
      - "service.namespace=${SERVICE_NAMESPACE:-quickpizza}"
    environment:
      <<: *quickpizza-env-common
      QUICKPIZZA_ENABLE_RECOMMENDATIONS_SERVICE: "1"
      QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID: "recommendations"
      QUICKPIZZA_OTEL_SERVICE_NAME: "recommendations"

  ws:
    image: ${QUICKPIZZA_IMAGE:-ghcr.io/grafana/quickpizza-local:0.15.20}
    container_name: ws
    labels:
      - "service.type=application"
      - "service.namespace=${SERVICE_NAMESPACE:-quickpizza}"
    environment:
      <<: *quickpizza-env-common
      QUICKPIZZA_ENABLE_WS_SERVICE: "1"
      QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID: "ws"
      QUICKPIZZA_OTEL_SERVICE_NAME: "ws"

  grpc:
    image: ${QUICKPIZZA_IMAGE:-ghcr.io/grafana/quickpizza-local:0.15.19}
    container_name: grpc
    labels:
      - "service.type=application"
      - "service.namespace=${SERVICE_NAMESPACE:-quickpizza}"
    ports:
      - "3334:3334"
      - "3335:3335"
    environment:
      <<: *quickpizza-env-common
      QUICKPIZZA_ENABLE_GRPC_SERVICE: "1"
      QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID: "grpc"
      QUICKPIZZA_OTEL_SERVICE_NAME: "grpc"

  quickpizza-db:
    image: postgres:18.1
    container_name: quickpizza-db
    labels:
      - "service.type=database"
      - "service.namespace=${SERVICE_NAMESPACE:-quickpizza}"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quickpizza_db
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  loki:
    image: grafana/loki:3.4.3
    container_name: loki
    labels:
      - "service.type=instrumentation"
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:v3.9.1
    container_name: prometheus
    labels:
      - "service.type=instrumentation"
    volumes:
      - ./deployments/docker-compose/grafana-local-stack/prometheus.yaml:/etc/prometheus.yaml
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus.yaml
    ports:
      - "9090:9090"

  pyroscope:
    image: grafana/pyroscope:1.16.0
    container_name: pyroscope
    labels:
      - "service.type=instrumentation"
    ports:
      - "4040:4040"

  tempo:
    image: grafana/tempo:2.9.0
    container_name: tempo
    labels:
      - "service.type=instrumentation"
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./deployments/docker-compose/grafana-local-stack/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200" # Tempo API/UI
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-12.2.0}
    container_name: grafana
    labels:
      - "service.type=instrumentation"
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_FEATURE_TOGGLES_ENABLE=tempoAlerting
    volumes:
      - ./deployments/docker-compose/grafana-local-stack/grafana:/etc/grafana/provisioning/

volumes:
  postgres_data:
