services:
  alloy:
    image: grafana/alloy:v1.11.3@sha256:8c7256f412feb9f5f48f9f6f9394dc97ca887f63dea9304f347970ecc1787669
    container_name: alloy
    labels:
      - "service.type=instrumentation"
    volumes:
      - "./alloy/${ALLOY_FILE_NAME:-cloud.alloy}:/config.alloy:Z"
      - "${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock"
    command:
      - run
      - /config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --stability.level=public-preview
    ports:
      - "12345:12345"
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    environment:
      QUICKPIZZA_HOST: quickpizza:3333
      # must be set with an .env file
      GRAFANA_CLOUD_TOKEN: "${GRAFANA_CLOUD_TOKEN}"
      GRAFANA_CLOUD_STACK: "${GRAFANA_CLOUD_STACK}"
      DEPLOYMENT_ENVIRONMENT: ${DEPLOYMENT_ENVIRONMENT:-development}
    depends_on:
      - quickpizza
  quickpizza:
    # The QUICKPIZZA_IMAGE env. variable enables the use of a locally built image,
    # created with `make docker-build`.
    image: ${QUICKPIZZA_IMAGE:-ghcr.io/grafana/quickpizza-local:0.15.11}
    # Alloy reads `container_name` to relabel service name in telemetry.
    container_name: quickpizza
    labels:
      - "service.type=application"
      - "service.namespace=${SERVICE_NAMESPACE:-quickpizza}"
    ports:
      - "3333:3333"
    environment:
      QUICKPIZZA_OTLP_ENDPOINT: http://alloy:4318
      QUICKPIZZA_TRUST_CLIENT_TRACEID: 1
      QUICKPIZZA_ENABLE_ALL_SERVICES: 1 # 1 for monolithic mode
      QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID: "quickpizza"
      QUICKPIZZA_OTEL_SERVICE_NAME: "quickpizza"
      # enable Faro integration
      QUICKPIZZA_CONF_FARO_URL: "${QUICKPIZZA_CONF_FARO_URL:-}"
      QUICKPIZZA_CONF_FARO_APP_NAME: "${QUICKPIZZA_CONF_FARO_APP_NAME:-}"
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=${DEPLOYMENT_ENVIRONMENT:-development},service.version=quickpizza-local"
