x-quickpizza-env-common: &quickpizza-env-common
  QUICKPIZZA_OTLP_ENDPOINT: http://alloy:4318
  QUICKPIZZA_TRUST_CLIENT_TRACEID: true
  QUICKPIZZA_ENABLE_ALL_SERVICES: 0 # 0 for microservice mode
  QUICKPIZZA_CATALOG_ENDPOINT: http://catalog:3333
  QUICKPIZZA_COPY_ENDPOINT: http://copy:3333
  QUICKPIZZA_WS_ENDPOINT: http://ws:3333
  QUICKPIZZA_RECOMMENDATIONS_ENDPOINT: http://recommendations:3333
  QUICKPIZZA_CONFIG_ENDPOINT: http://config:3333

name: quickpizza
services:
  alloy:
    image: grafana/alloy:v1.9.1@sha256:b5fc87ff9a8941d6ed3ae5f099d9cb8598b3cd42fef9a8af128ed782258b4017
    container_name: alloy
    labels:
      - "service.type=instrumentation"
    volumes:
      - "./alloy/${ALLOY_FILE_NAME:-local.alloy}:/config.alloy:Z"
      - "${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock"
    command:
      - run
      - /config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --stability.level=public-preview
    ports:
      - "12345:12345"
    environment:
      QUICKPIZZA_HOST: quickpizza:3333
      METRICS_ENDPOINT: http://prometheus:9090/api/v1/write
      TRACES_ENDPOINT: http://tempo:4317
      LOGS_ENDPOINT: http://loki:3100/loki/api/v1/push
      PROFILES_ENDPOINT: http://pyroscope:4040
    depends_on:
      - prometheus
      - tempo
      - pyroscope
      - catalog
      - config
      - copy
      - public-api
      - recommendations
      - ws

  catalog:
    image: ${QUICKPIZZA_IMAGE:-ghcr.io/grafana/quickpizza-local:latest@sha256:9067de15119819a3ef17676b3245279937d9d9ef50e81a2ba0a8a30095d7bfce}
    container_name: catalog
    labels:
      - "service.type=application"
    environment:
      <<: *quickpizza-env-common
      QUICKPIZZA_ENABLE_CATALOG_SERVICE: "1"
      QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID: "catalog"
      QUICKPIZZA_OTEL_SERVICE_NAME: "catalog"

  config:
    image: ${QUICKPIZZA_IMAGE:-ghcr.io/grafana/quickpizza-local:latest@sha256:9067de15119819a3ef17676b3245279937d9d9ef50e81a2ba0a8a30095d7bfce}
    container_name: config
    labels:
      - "service.type=application"
    environment:
      <<: *quickpizza-env-common
      QUICKPIZZA_ENABLE_CONFIG_SERVICE: "1"
      QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID: "config"
      QUICKPIZZA_OTEL_SERVICE_NAME: "config"
  copy:
    image: ${QUICKPIZZA_IMAGE:-ghcr.io/grafana/quickpizza-local:latest@sha256:9067de15119819a3ef17676b3245279937d9d9ef50e81a2ba0a8a30095d7bfce}
    container_name: copy
    labels:
      - "service.type=application"
    environment:
      <<: *quickpizza-env-common
      QUICKPIZZA_ENABLE_COPY_SERVICE: "1"
      QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID: "copy"
      QUICKPIZZA_OTEL_SERVICE_NAME: "copy"

  public-api:
    image: ${QUICKPIZZA_IMAGE:-ghcr.io/grafana/quickpizza-local:latest@sha256:9067de15119819a3ef17676b3245279937d9d9ef50e81a2ba0a8a30095d7bfce}
    container_name: public-api
    labels:
      - "service.type=application"
    ports:
      - "3333:3333"
    environment:
      <<: *quickpizza-env-common
      QUICKPIZZA_ENABLE_PUBLIC_API_SERVICE: "1"
      QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID: "public-api"
      QUICKPIZZA_OTEL_SERVICE_NAME: "public-api"

  recommendations:
    image: ${QUICKPIZZA_IMAGE:-ghcr.io/grafana/quickpizza-local:latest@sha256:9067de15119819a3ef17676b3245279937d9d9ef50e81a2ba0a8a30095d7bfce}
    container_name: recommendations
    labels:
      - "service.type=application"
    environment:
      <<: *quickpizza-env-common
      QUICKPIZZA_ENABLE_RECOMMENDATIONS_SERVICE: "1"
      QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID: "recommendations"
      QUICKPIZZA_OTEL_SERVICE_NAME: "recommendations"

  ws:
    image: ${QUICKPIZZA_IMAGE:-ghcr.io/grafana/quickpizza-local:latest@sha256:9067de15119819a3ef17676b3245279937d9d9ef50e81a2ba0a8a30095d7bfce}
    container_name: ws
    labels:
      - "service.type=application"
    environment:
      <<: *quickpizza-env-common
      QUICKPIZZA_ENABLE_WS_SERVICE: "1"
      QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID: "ws"
      QUICKPIZZA_OTEL_SERVICE_NAME: "ws"

  loki:
    image: grafana/loki:3.4.3@sha256:5fe9fa99e9a747297cdf0239a5b25d192d8f668bd6505b09beef4dffcab5aac2
    container_name: loki
    labels:
      - "service.type=instrumentation"
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:v3.2.1@sha256:6927e0919a144aa7616fd0137d4816816d42f6b816de3af269ab065250859a62
    container_name: prometheus
    labels:
      - "service.type=instrumentation"
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  pyroscope:
    image: grafana/pyroscope:1.14.0@sha256:0f63959ffcf217e7046d8f7a3d20cf6909f2924f885fc2f0eec58f87f9acf749
    container_name: pyroscope
    labels:
      - "service.type=instrumentation"
    ports:
      - "4040:4040"

  tempo:
    image: grafana/tempo:2.9.0@sha256:65a5789759435f1ef696f1953258b9bbdb18eb571d5ce711ff812d2e128288a4
    container_name: tempo
    labels:
      - "service.type=instrumentation"
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./alloy/local-tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-12.2.0}
    container_name: grafana
    labels:
      - "service.type=instrumentation"
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_FEATURE_TOGGLES_ENABLE=tempoAlerting
    volumes:
      - ./grafana:/etc/grafana/provisioning/
