x-quickpizza-env-common: &quickpizza-env-common
  QUICKPIZZA_OTLP_ENDPOINT: http://alloy:4318
  QUICKPIZZA_TRUST_CLIENT_TRACEID: true
  QUICKPIZZA_ENABLE_ALL_SERVICES: 0 # 0 for microservice mode
  QUICKPIZZA_CATALOG_ENDPOINT: http://catalog:3333
  QUICKPIZZA_COPY_ENDPOINT: http://copy:3333
  QUICKPIZZA_WS_ENDPOINT: http://ws:3333
  QUICKPIZZA_RECOMMENDATIONS_ENDPOINT: http://recommendations:3333
  QUICKPIZZA_CONFIG_ENDPOINT: http://config:3333
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=${DEPLOYMENT_ENVIRONMENT:-development},service.version=quickpizza-local"

name: quickpizza
services:
  alloy:
    image: grafana/alloy:v1.12.2@sha256:f94b1c82957accb77cd11385fd5e3600758ef1b1ab79557c97319ad28590735a
    container_name: alloy
    labels:
      - "service.type=instrumentation"
    volumes:
      - "./deployments/docker-compose/grafana-cloud/${ALLOY_FILE_NAME:-config.alloy}:/config.alloy:Z"
      - "${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock"
    command:
      - run
      - /config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --stability.level=public-preview
    ports:
      - "12345:12345"
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    environment:
      QUICKPIZZA_HOST: public-api:3333
      # must be set with an .env file
      GRAFANA_CLOUD_TOKEN: "${GRAFANA_CLOUD_TOKEN}"
      GRAFANA_CLOUD_STACK: "${GRAFANA_CLOUD_STACK}"
      DEPLOYMENT_ENVIRONMENT: ${DEPLOYMENT_ENVIRONMENT:-development}
      # Use empty string to disable.
      DB_O11Y_CONNECTION: "${DB_O11Y_CONNECTION-postgres://db-o11y:db-o11y-password@quickpizza-db:5432/quickpizza_db?sslmode=disable}"
      SERVICE_NAMESPACE: "${SERVICE_NAMESPACE:-quickpizza}"
      DB_SERVICE_NAME: "quickpizza-db"
    depends_on:
      - catalog
      - config
      - copy
      - public-api
      - recommendations
      - ws
      - grpc

  catalog:
    image: ${QUICKPIZZA_IMAGE:-ghcr.io/grafana/quickpizza-local:0.15.21@sha256:de839571c65ce9ac6e96290f44a7122869f31744d93bd235903ecb9429158d32}
    container_name: catalog
    labels:
      - "service.type=application"
      - "service.namespace=${SERVICE_NAMESPACE:-quickpizza}"
    environment:
      <<: *quickpizza-env-common
      QUICKPIZZA_ENABLE_CATALOG_SERVICE: "1"
      QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID: "catalog"
      QUICKPIZZA_OTEL_SERVICE_NAME: "catalog"
      # QUICKPIZZA_DB unset set to postgres. If empty, set to sqlite.
      QUICKPIZZA_DB: "${QUICKPIZZA_DB-postgres://postgres:postgres@quickpizza-db:5432/quickpizza_db?sslmode=disable}"
      # OTEL `db.name` span attribute. Used by servicegraph to create service nodes with this name
      # Set to the logical database service name
      QUICKPIZZA_OTEL_DB_NAME: "quickpizza-db"
    depends_on:
      quickpizza-db:
        condition: service_healthy

  config:
    image: ${QUICKPIZZA_IMAGE:-ghcr.io/grafana/quickpizza-local:0.15.21@sha256:de839571c65ce9ac6e96290f44a7122869f31744d93bd235903ecb9429158d32}
    container_name: config
    labels:
      - "service.type=application"
      - "service.namespace=${SERVICE_NAMESPACE:-quickpizza}"
    environment:
      <<: *quickpizza-env-common
      QUICKPIZZA_ENABLE_CONFIG_SERVICE: "1"
      QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID: "config"
      QUICKPIZZA_OTEL_SERVICE_NAME: "config"
      # enable Faro integration
      QUICKPIZZA_CONF_FARO_URL: "${QUICKPIZZA_CONF_FARO_URL:-}"
      QUICKPIZZA_CONF_FARO_APP_NAME: "${QUICKPIZZA_CONF_FARO_APP_NAME:-QuickPizza}"
      QUICKPIZZA_CONF_FARO_INSTRUMENTATION_ENABLE_REPLAY: "${QUICKPIZZA_CONF_FARO_INSTRUMENTATION_ENABLE_REPLAY:-false}"
  copy:
    image: ${QUICKPIZZA_IMAGE:-ghcr.io/grafana/quickpizza-local:0.15.21@sha256:de839571c65ce9ac6e96290f44a7122869f31744d93bd235903ecb9429158d32}
    container_name: copy
    labels:
      - "service.type=application"
      - "service.namespace=${SERVICE_NAMESPACE:-quickpizza}"
    environment:
      <<: *quickpizza-env-common
      QUICKPIZZA_ENABLE_COPY_SERVICE: "1"
      QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID: "copy"
      QUICKPIZZA_OTEL_SERVICE_NAME: "copy"
      # QUICKPIZZA_DB unset set to postgres. If empty, set to sqlite.
      QUICKPIZZA_DB: "${QUICKPIZZA_DB-postgres://postgres:postgres@quickpizza-db:5432/quickpizza_db?sslmode=disable}"
      # OTEL `db.name` span attribute. Used by servicegraph to create service nodes with this name
      # Set to the logical database service name
      QUICKPIZZA_OTEL_DB_NAME: "quickpizza-db"
    depends_on:
      quickpizza-db:
        condition: service_healthy
      catalog: # avoid race condition for db migrations
        condition: service_started

  public-api:
    image: ${QUICKPIZZA_IMAGE:-ghcr.io/grafana/quickpizza-local:0.15.21@sha256:de839571c65ce9ac6e96290f44a7122869f31744d93bd235903ecb9429158d32}
    container_name: public-api
    labels:
      - "service.type=application"
      - "service.namespace=${SERVICE_NAMESPACE:-quickpizza}"
    ports:
      - "3333:3333"
    environment:
      <<: *quickpizza-env-common
      QUICKPIZZA_ENABLE_PUBLIC_API_SERVICE: "1"
      QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID: "public-api"
      QUICKPIZZA_OTEL_SERVICE_NAME: "public-api"

  recommendations:
    image: ${QUICKPIZZA_IMAGE:-ghcr.io/grafana/quickpizza-local:0.15.21@sha256:de839571c65ce9ac6e96290f44a7122869f31744d93bd235903ecb9429158d32}
    container_name: recommendations
    labels:
      - "service.type=application"
      - "service.namespace=${SERVICE_NAMESPACE:-quickpizza}"
    environment:
      <<: *quickpizza-env-common
      QUICKPIZZA_ENABLE_RECOMMENDATIONS_SERVICE: "1"
      QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID: "recommendations"
      QUICKPIZZA_OTEL_SERVICE_NAME: "recommendations"

  ws:
    image: ${QUICKPIZZA_IMAGE:-ghcr.io/grafana/quickpizza-local:0.15.21@sha256:de839571c65ce9ac6e96290f44a7122869f31744d93bd235903ecb9429158d32}
    container_name: ws
    labels:
      - "service.type=application"
      - "service.namespace=${SERVICE_NAMESPACE:-quickpizza}"
    environment:
      <<: *quickpizza-env-common
      QUICKPIZZA_ENABLE_WS_SERVICE: "1"
      QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID: "ws"
      QUICKPIZZA_OTEL_SERVICE_NAME: "ws"

  grpc:
    image: ${QUICKPIZZA_IMAGE:-ghcr.io/grafana/quickpizza-local:0.15.21@sha256:de839571c65ce9ac6e96290f44a7122869f31744d93bd235903ecb9429158d32}
    container_name: grpc
    labels:
      - "service.type=application"
      - "service.namespace=${SERVICE_NAMESPACE:-quickpizza}"
    ports:
      - "3334:3334"
    environment:
      <<: *quickpizza-env-common
      QUICKPIZZA_ENABLE_GRPC_SERVICE: "1"
      QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID: "grpc"
      QUICKPIZZA_OTEL_SERVICE_NAME: "grpc"

  quickpizza-db:
    image: postgres:18.1@sha256:1090bc3a8ccfb0b55f78a494d76f8d603434f7e4553543d6e807bc7bd6bbd17f
    container_name: quickpizza-db
    labels:
      - "service.type=database"
      - "service.namespace=${SERVICE_NAMESPACE:-quickpizza}"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quickpizza_db
      DB_O11Y_USER: db-o11y
      DB_O11Y_PASSWORD: db-o11y-password
      DB_O11Y_DATABASES: quickpizza_db
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./deployments/init-db-observability.sh:/docker-entrypoint-initdb.d/init-db-observability.sh:Z
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "track_activity_query_size=4096"
      - "-c"
      - "pg_stat_statements.track=all"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
