services:
  alloy:
    image: grafana/alloy:v1.12.0
    container_name: alloy
    labels:
      - "service.type=instrumentation"
    volumes:
      - "./alloy/${ALLOY_FILE_NAME:-cloud.alloy}:/config.alloy:Z"
      - "${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock"
    command:
      - run
      - /config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --stability.level=public-preview
    ports:
      - "12345:12345"
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    environment:
      QUICKPIZZA_HOST: quickpizza:3333
      # must be set with an .env file
      GRAFANA_CLOUD_TOKEN: "${GRAFANA_CLOUD_TOKEN}"
      GRAFANA_CLOUD_STACK: "${GRAFANA_CLOUD_STACK}"
      DEPLOYMENT_ENVIRONMENT: ${DEPLOYMENT_ENVIRONMENT:-development}
      QUICKPIZZA_DB: "${QUICKPIZZA_DB-postgres://postgres:postgres@quickpizza-db:5432/quickpizza_db?sslmode=disable}"
      SERVICE_NAMESPACE: "${SERVICE_NAMESPACE:-quickpizza}"
      DB_SERVICE_NAME: "quickpizza-db"
    depends_on:
      - quickpizza
  quickpizza:
    # The QUICKPIZZA_IMAGE env. variable enables the use of a locally built image,
    # created with `make docker-build`.
    image: ${QUICKPIZZA_IMAGE:-ghcr.io/grafana/quickpizza-local:0.15.14}
    # Alloy reads `container_name` to relabel service name in telemetry.
    container_name: quickpizza
    labels:
      - "service.type=application"
      - "service.namespace=${SERVICE_NAMESPACE:-quickpizza}"
    ports:
      - "3333:3333"
    environment:
      QUICKPIZZA_OTLP_ENDPOINT: http://alloy:4318
      QUICKPIZZA_TRUST_CLIENT_TRACEID: 1
      QUICKPIZZA_ENABLE_ALL_SERVICES: 1 # 1 for monolithic mode
      QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID: "quickpizza"
      QUICKPIZZA_OTEL_SERVICE_NAME: "quickpizza"
      # enable Faro integration
      QUICKPIZZA_CONF_FARO_URL: "${QUICKPIZZA_CONF_FARO_URL:-}"
      QUICKPIZZA_CONF_FARO_APP_NAME: "${QUICKPIZZA_CONF_FARO_APP_NAME:-}"
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=${DEPLOYMENT_ENVIRONMENT:-development},service.version=quickpizza-local"
      # OTEL `db.name` span attribute. Used by servicegraph to create service nodes with this name
      # Set to the logical database service name
      QUICKPIZZA_OTEL_DB_NAME: "quickpizza-db"
      # QUICKPIZZA_DB unset set to postgres. If empty, set to sqlite.
      QUICKPIZZA_DB: "${QUICKPIZZA_DB-postgres://postgres:postgres@quickpizza-db:5432/quickpizza_db?sslmode=disable}"
    depends_on:
      quickpizza-db:
        condition: service_healthy

  quickpizza-db:
    image: postgres:18.1
    container_name: quickpizza-db
    labels:
      - "service.type=database"
      - "service.namespace=${SERVICE_NAMESPACE:-quickpizza}"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quickpizza_db
      DB_O11Y_USER: db-o11y
      DB_O11Y_PASSWORD: db-o11y-password
      DB_O11Y_DATABASES: quickpizza_db
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./scripts/init-db-observability.sh:/docker-entrypoint-initdb.d/init-db-observability.sh:Z
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "track_activity_query_size=4096"
      - "-c"
      - "pg_stat_statements.track=all"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
