services:
  quickpizza:
    # The QUICKPIZZA_IMAGE env. variable enables the use of a locally built image,
    # created with `make docker-build`.
    image: ${QUICKPIZZA_IMAGE:-ghcr.io/grafana/quickpizza-local:latest}
    ports:
      - "3333:3333"
    environment:
      QUICKPIZZA_OTLP_ENDPOINT: http://alloy:4318
      QUICKPIZZA_TRUST_CLIENT_TRACEID: 1
      QUICKPIZZA_PYROSCOPE_ENDPOINT: http://alloy:9999
      # Enable logging. Possible values: error, warn, debug. Default: info
      # QUICKPIZZA_LOG_LEVEL: debug

  loki:
    image: grafana/loki:3.4.3
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:v3.2.1
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  pyroscope:
    image: grafana/pyroscope:1.14.0
    ports:
      - "4040:4040"
  
  tempo:
    image: grafana/tempo:2.8.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./alloy/local-tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-12.1.0}
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/

  alloy:
    image: grafana/alloy:v1.9.1
    volumes:
      - "./alloy/local.alloy:/config.alloy:Z"
      - "./alloy/${ALLOY_FILE_NAME:-local.alloy}:/config.alloy:Z"
      - "${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock"
    command:
      - run
      - /config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --stability.level=public-preview
    ports:
      - "12345:12345"
    environment:
      QUICKPIZZA_HOST: quickpizza:3333
      METRICS_ENDPOINT: http://prometheus:9090/api/v1/write
      TRACES_ENDPOINT: http://tempo:4317
      LOGS_ENDPOINT: http://loki:3100/loki/api/v1/push
      PROFILES_ENDPOINT: http://pyroscope:4040
    depends_on:
      - prometheus
      - quickpizza
      - tempo
      - pyroscope
