FROM node:16.19.1-bullseye

WORKDIR /app
COPY . .
WORKDIR /app/pkg/web
RUN npm install
WORKDIR /app

RUN apt-get update && apt-get install -y wget
RUN wget https://golang.org/dl/go1.18.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.18.linux-amd64.tar.gz
ENV PATH=$PATH:/usr/local/go/bin

EXPOSE 3333
