{
 "title": "QuickPizza Logs",
 "tags": [ "Logs" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 19, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"padding: 3px;\">\n  <div style=\"margin-bottom: 3px;display: flex; flex-direction: row; align-items: center; margin-top: 3px;\">\n    <img style=\"height: 40px; width: 40px; margin-right: 10px;\" src=\"https://files.readme.io/e5e1b43-grafana-loki.png\" />\n    <h1 style=\"margin-top: 5px;\">QuickPizza Logs Demo Dashboard</h1>\n  </div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
   "options": {
    "content": "---\n<div style=\"padding: 10px;\">\n\n### **Pre-configured Log Panels**\nThe panels below offer an introductory setup so you start observing Demo Logs. All of these panels are dynamic so you can view, share, share and inspect the data in each panel.\n\n---\n##### 💡 Tips\n- Hover over the ℹ️ icon to read a full description of what's included on each panel\n- Adjust the timepicker to select relative time range options and set custom absolute time ranges\n- Useful keyboard shortcuts for dashboards: \n   - `Ctrl+S` : Saves the current dashboard\n   - `f`: Opens the dashboard finder / search\n   - `d+s`: Dashboard settings"
   }
  },
  {
   "title": "Total Info Logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service_namespace=\"quickpizza\"} | detected_level=\"info\" [$__range]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Total Warn Logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service_namespace=\"quickpizza\"} | detected_level=\"warn\" [$__range]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Total Error Logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service_namespace=\"quickpizza\"} | detected_level=\"error\" [$__range]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({service_namespace=\"quickpizza\"} [$__auto])) by (detected_level)",
     "legendFormat": "{{ detected_level }}"
    }
   ]
  },
  {
   "title": "Distribution by Log Level",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service_namespace=\"quickpizza\"} [$__range])) by (detected_level)",
     "legendFormat": "{{detected_level}}"
    }
   ]
  },
  {
   "title": "Distribution by Path",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service_namespace=\"quickpizza\"} | json | httpRequest_path=~\"/api/.*\" [$__range])) by (httpRequest_path)",
     "legendFormat": "{{ httpRequest_path }}"
    }
   ]
  },
  {
   "title": "Distribution by Method",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service_namespace=\"quickpizza\"} | json | httpRequest_path=~\"/api/.*\" [$__range])) by (httpRequest_method)",
     "legendFormat": "{{httpRequest_method}}"
    }
   ]
  },
  {
   "title": "Distribution by Status Code",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service_namespace=\"quickpizza\"} | json | httpRequest_path=~\"/api/.*\" [$__range])) by (httpResponse_status)",
     "legendFormat": "200"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{service_namespace=\"quickpizza\"} |= ``"
    }
   ]
  }
 ]
}