{
 "title": "QuickPizza Service Performance",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "component",
    "label": "Component",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{\"service_namespace\"=\"quickpizza\"},service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 18, "x": 0, "y": 0 },
   "options": {
    "content": "# Performance & RED Metrics\nThis dashboard shows the [RED metrics](https://grafana.com/blog/2018/08/02/the-red-method-how-to-instrument-your-services/) for all components. Use the selector above this panel to change the service you are inspecting.\nIt also summarizes request volume and database query count for quick analysis."
   }
  },
  { "type": "text", "gridPos": { "h": 1, "w": 6, "x": 18, "y": 0 } },
  {
   "title": "Frontend Response Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(http_server_request_duration_seconds_bucket{service_name=~\".*public-api\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95 "
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(http_server_request_duration_seconds_bucket{service_name=~\".*public-api\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.90,sum(rate(http_server_request_duration_seconds_bucket{service_name=~\".*public-api\"}[$__rate_interval])) by (le))",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "Request Volume",
   "type": "stat",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(quickpizza_server_http_request_duration_seconds_count{service_namespace=\"quickpizza\", service_name=~\"$component\"}[$__rate_interval])) by (service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  { "title": "Details for $component", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "component" },
  {
   "title": "Request rate by path",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(quickpizza_server_http_request_duration_seconds_count{service_namespace=\"quickpizza\", service_name=\"$component\"}[$__rate_interval])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(http_server_request_duration_seconds_bucket{service_namespace=\"quickpizza\", service_name=\"$component\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95 - $component"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(http_server_request_duration_seconds_bucket{service_namespace=\"quickpizza\", service_name=\"$component\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99 - $component"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_sum{service_namespace=\"quickpizza\", service_name=\"$component\"}[$__rate_interval])) / sum(rate(http_server_request_duration_seconds_count{service_namespace=\"quickpizza\", service_name=\"$component\"}[$__rate_interval]))",
     "legendFormat": "Avg - $component"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(quickpizza_server_http_request_duration_seconds_sum{service_name=\"$component\",status!~\"(2..|0)\"}[$__rate_interval])) / sum(rate(quickpizza_server_http_request_duration_seconds_sum{service_name=\"$component\"}[$__rate_interval]))) or vector(0)",
     "legendFormat": "Error Rate"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 }, "options": { "content": "---" } }
 ]
}