apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-alloy
  labels:
    app.k8s.io/name: grafana-alloy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.k8s.io/name: grafana-alloy
  template:
    metadata:
      name: grafana-alloy
      labels:
        app.k8s.io/name: grafana-alloy
    spec:
      restartPolicy: Always
      serviceAccountName: grafana-alloy
      containers:
        - name: grafana-alloy
          image: grafana/alloy:v1.9.1
          imagePullPolicy: IfNotPresent
          args:
            - run
            - /etc/alloy-config/grafana-alloy.river
          envFrom:
            - secretRef:
                name: grafana-alloy-credentials
          ports:
            - name: grpc
              containerPort: 4317
            - name: http
              containerPort: 4318
          volumeMounts:
            - mountPath: /etc/alloy-config/grafana-alloy.river
              name: alloy-config
              subPath: grafana-alloy.river
      volumes:
        - name: alloy-config
          configMap:
            name: alloy-config
