#!/bin/bash

# Script to generate BuildConfig.swift from Config.xcconfig
# This script runs during the build phase and creates Swift constants from xcconfig variables

set -e

CONFIG_FILE="${SRCROOT}/Config.xcconfig"
OUTPUT_FILE="${SRCROOT}/QuickPizzaIos/Core/Config/BuildConfig.generated.swift"

# Check if Config.xcconfig exists
if [ ! -f "$CONFIG_FILE" ]; then
    echo "Warning: Config.xcconfig not found at ${CONFIG_FILE}"
    echo "Using default values from Config.xcconfig.example"
    CONFIG_FILE="${SRCROOT}/Config.xcconfig.example"
fi

# Parse xcconfig file and extract values
function get_xcconfig_value() {
    local key=$1
    local value=$(grep "^${key} = " "$CONFIG_FILE" | cut -d '=' -f2- | sed 's/^ *//' | sed 's/ *$//')
    # Handle the $()/  escape sequence used in xcconfig for URLs
    value=$(echo "$value" | sed 's/\$()//g')
    # Remove surrounding quotes if present
    value=$(echo "$value" | sed 's/^"\(.*\)"$/\1/')
    echo "$value"
}

BASE_URL=$(get_xcconfig_value "BASE_URL")
PORT=$(get_xcconfig_value "PORT")
OTLP_ENDPOINT=$(get_xcconfig_value "OTLP_ENDPOINT")
OTLP_AUTH_HEADER=$(get_xcconfig_value "OTLP_AUTH_HEADER")

# Generate Swift file with proper optional handling
cat > "$OUTPUT_FILE" << EOF
// This file is auto-generated by Scripts/generate-config.sh
// Do not edit manually - changes will be overwritten on next build
// Generated from Config.xcconfig

import Foundation

enum BuildConfig {
EOF

# Add baseURL
if [ -n "$BASE_URL" ]; then
    echo "    static let baseURL: String? = \"$BASE_URL\"" >> "$OUTPUT_FILE"
else
    echo "    static let baseURL: String? = nil" >> "$OUTPUT_FILE"
fi

# Add port
if [ -n "$PORT" ]; then
    echo "    static let port: String? = \"$PORT\"" >> "$OUTPUT_FILE"
else
    echo "    static let port: String? = nil" >> "$OUTPUT_FILE"
fi

# Add otlpEndpoint
if [ -n "$OTLP_ENDPOINT" ]; then
    echo "    static let otlpEndpoint: String? = \"$OTLP_ENDPOINT\"" >> "$OUTPUT_FILE"
else
    echo "    static let otlpEndpoint: String? = nil" >> "$OUTPUT_FILE"
fi

# Add otlpAuthHeader
if [ -n "$OTLP_AUTH_HEADER" ]; then
    echo "    static let otlpAuthHeader: String? = \"$OTLP_AUTH_HEADER\"" >> "$OUTPUT_FILE"
else
    echo "    static let otlpAuthHeader: String? = nil" >> "$OUTPUT_FILE"
fi

echo "}" >> "$OUTPUT_FILE"

echo "✅ Generated BuildConfig.swift from Config.xcconfig"
