#!/bin/bash

# Script to generate BuildConfig.swift from Config.xcconfig
# This script runs during the build phase and creates Swift constants from xcconfig variables

set -e

CONFIG_FILE="${SRCROOT}/Config.xcconfig"
OUTPUT_FILE="${SRCROOT}/QuickPizzaIos/Core/Config/BuildConfig.generated.swift"

# Check if Config.xcconfig exists
if [ ! -f "$CONFIG_FILE" ]; then
    echo "Warning: Config.xcconfig not found at ${CONFIG_FILE}"
    echo "Using default values from Config.xcconfig.example"
    CONFIG_FILE="${SRCROOT}/Config.xcconfig.example"
fi

# Parse xcconfig file and extract values
function get_xcconfig_value() {
    local key=$1
    local value=$(grep "^${key} = " "$CONFIG_FILE" | cut -d '=' -f2- | sed 's/^ *//' | sed 's/ *$//')
    # Handle the $()/  escape sequence used in xcconfig for URLs
    value=$(echo "$value" | sed 's/\$()//g')
    # Remove surrounding quotes if present
    value=$(echo "$value" | sed 's/^"\(.*\)"$/\1/')
    echo "$value"
}

BASE_URL=$(get_xcconfig_value "BASE_URL")
PORT=$(get_xcconfig_value "PORT")
OTLP_ENDPOINT=$(get_xcconfig_value "OTLP_ENDPOINT")
OTLP_INSTANCE_ID=$(get_xcconfig_value "OTLP_INSTANCE_ID")
OTLP_API_KEY=$(get_xcconfig_value "OTLP_API_KEY")

# Generate Swift file with proper optional handling
cat > "$OUTPUT_FILE" << EOF
// This file is auto-generated by Scripts/generate-config.sh
// Do not edit manually - changes will be overwritten on next build
// Generated from Config.xcconfig

import Foundation

enum BuildConfig {
EOF

function emit_string_optional() {
    local name=$1
    local value=$2
    if [ -n "$value" ]; then
        echo "    static let ${name}: String? = \"${value}\"" >> "$OUTPUT_FILE"
    else
        echo "    static let ${name}: String? = nil" >> "$OUTPUT_FILE"
    fi
}

emit_string_optional "baseURL"        "$BASE_URL"
emit_string_optional "port"           "$PORT"
emit_string_optional "otlpEndpoint"   "$OTLP_ENDPOINT"
emit_string_optional "otlpInstanceId" "$OTLP_INSTANCE_ID"
emit_string_optional "otlpApiKey"     "$OTLP_API_KEY"

echo "}" >> "$OUTPUT_FILE"

echo "✅ Generated BuildConfig.swift from Config.xcconfig"
