# Uncomment the following line to deploy the application on a non-default namespace
#namespace: quickpizza

resources:
  - ./resources/deployments.yaml
  - ./resources/services.yaml

images:
  - name: ghcr.io/grafana/quickpizza-local
    # Uncomment the following lines to change the quickpizza image. 
    newName: local-quickpizza
    newTag: latest


