# For configuration options, see
#   https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file

apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false
      timeInterval: 60s # Scrape interval (should match Prometheus configuration, defined in local.alloy)
    editable: false
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      # activate service map and node graph features (required Alloy config)
      serviceMap:
        datasourceUid: "prometheus"
      nodeGraph:
        enabled: true
  - name: Pyroscope
    type: "phlare"
    uid: pyroscope
    access: "proxy"
    orgId: 1
    url: http://pyroscope:4040
    isDefault: false
    editable: false
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: tid=(\w+)
          name: TraceID
          url: $${__value.raw}
