resources:
  - ../base
  - ../base/resources/grafana-alloy

# For telemetry functionality, change the following lines to match your configuration.
secretGenerator:
  - name: grafana-alloy-credentials
    envs:
    - .env

# You can use the following generator to add additional environment variables to all QuickPizza pods.
configMapGenerator:
  - name: quickpizza-env
    literals:
      # Trust all incoming TraceIDs for demo purposes.
      - QUICKPIZZA_TRUST_CLIENT_TRACEID=true
      # You can change other settings by adding entries to this list:
      #- CUSTOM_ENV=CUSTOM_VALUE
  - name: alloy-config
    files:
      - ./config/config.alloy
  - name: tracing-env
    literals:
      - QUICKPIZZA_OTLP_ENDPOINT=http://grafana-alloy:4318
