name: Build and Test (without Docker)
on: [push]

permissions:
  contents: read

jobs:
  runner-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Setup Goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Check Formatting (Go)
        run: make format-check

      - name: Check Formatting (TypeScript)
        run: cd pkg/web && npm run lint

      - name: Build Binary
        run: make build

      - name: Start Server
        # Use enable these features in our own deployment, so we might as well
        # "enable" them during testing as well to simulate a more realistic setup.
        env:
          QUICKPIZZA_OTLP_ENDPOINT: "http://localhost"
          QUICKPIZZA_TRUST_CLIENT_TRACEID: "1"
          QUICKPIZZA_PYROSCOPE_ENDPOINT: "http://localhost"
        run: ./bin/quickpizza &

      - name: Setup k6
        uses: grafana/setup-k6-action@ffe7d7290dfa715e48c2ccc924d068444c94bde2 # v1

      - name: Install chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt update && sudo apt install -y google-chrome-stable

      - name: Install jq
        uses: dcarbone/install-jq-action@e397bd87438d72198f81efd21f876461183d383a # v3.0.1

      - name: Run k6 foundations tests
        run: ./scripts/run-tests.sh -t **/k6/foundations/*.js -u http://localhost:3333

      - name: Run k6 foundations TS tests
        run: ./scripts/run-tests.sh -t **/k6/foundations/*.ts -u http://localhost:3333

      - name: Run k6 internal tests
        run: ./scripts/run-tests.sh -t **/k6/internal/*.js -u http://localhost:3333

      - name: Run k6 browser tests
        run: ./scripts/run-tests.sh -t **/k6/browser/*.js -u http://localhost:3333

      - name: Stop Server
        run: pkill -9 quickpizza
