name: Verify scripts Workflow
on: [push]

jobs:
  basic_k6_test:
    name: k6 test run - verify scripts example
    runs-on: ubuntu-latest

    services:
      quickpizza:
        image: ghcr.io/grafana/quickpizza-local:0.15.21@sha256:de839571c65ce9ac6e96290f44a7122869f31744d93bd235903ecb9429158d32 # zizmor: ignore[unpinned-images]
        ports:
          - 3333:3333

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup k6
        uses: grafana/setup-k6-action@ffe7d7290dfa715e48c2ccc924d068444c94bde2 # v1
      - name: Verify test script
        uses: grafana/run-k6-action@de51a7390bdf0ac85a3bef493691bd71d4c7c158 # v1.4.0
        with:
          path: |
            ./k6/foundations/01.basic.js
          only-verify-scripts: true
