name: Browser Tests Workflow
on: [push]

jobs:
  k6_browser_tests:
    name: k6 test run - running all browser tests
    runs-on: ubuntu-latest

    services:
      quickpizza:
        image: ghcr.io/grafana/quickpizza-local:latest@sha256:9067de15119819a3ef17676b3245279937d9d9ef50e81a2ba0a8a30095d7bfce # zizmor: ignore[unpinned-images]
        ports:
          - 3333:3333

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        
      - name: Setup k6
        uses: grafana/setup-k6-action@ffe7d7290dfa715e48c2ccc924d068444c94bde2 # v1
        with:
          browser: true
      - name: Run k6 test
        uses: grafana/run-k6-action@a15e2072ede004e8d46141e33d7f7dad8ad08d9d # v1
        with:
          path: |
            ./k6/browser/*.js
